In [2]:
import numpy as np
import matplotlib.pyplot as plt
from scipy import misc
from PIL import Image

In [4]:
#create a ndarry from scratch
my_array = np.array([1.1, 9.2, 8.1, 4.7])
my_array.shape

(4,)

In [5]:
#accessing values from our array
my_array[2]

8.1

In [6]:
#Checking the dimension of the array
my_array.ndim

1

In [9]:
array_2d = np.array([[1, 2, 3, 9], [5, 6, 7, 8]])
array_2d.shape
array_2d.ndim

2

In [10]:
array_2d

array([[1, 2, 3, 9],
       [5, 6, 7, 8]])

In [11]:
#row and columns are start from 0 index.
array_2d[1,3]

8

In [12]:
#To access a entire row
array_2d[0,:]

array([1, 2, 3, 9])

In [13]:
mystery_array = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],
                        
                         [[7, 86, 6, 98],
                          [5, 1, 0, 4]],
                          
                          [[5, 36, 32, 48],
                           [97, 0, 27, 18]]])

In [19]:
mystery_array.shape

(3, 2, 4)

In [57]:
mystery_array[2,1, :]

array([97,  0, 27, 18])

In [56]:
mystery_array[:,:,0]

array([[ 0,  4],
       [ 7,  5],
       [ 5, 97]])

In [62]:
a = np.arange(10,30,1, dtype=int)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29])

In [74]:
print(a[17:20])
print(np.array([a[4:7]]))
print(a[12:20])
print(a[::-1])
        

[27 28 29]
[[14 15 16]]
[22 23 24 25 26 27 28 29]
[29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]
